### ISSUE TITLE
pytlsd submodule problem

### ISSUE THREAD

**Issue by zachanton** [cvg/DeepLSD#1]
You have some problem with [pytlsd](https://github.com/rpautrat/pytlsd/tree/3b362891160aec45cf227095558f1cf3d322cf5b), it's not working.

**Comment by rpautrat** [comment]
Hi, can you be more specific about your issue, e.g. by describing and pasting your error message?

**Comment by zachanton** [comment]
The link pytlsd @ 3b36289 in the DeepLSD/third_party folder does not open, the other links in the folder do. Also, I can't install this library with git clone --recurse-submodules.

**Comment by rpautrat** [comment]
Thanks for reporting it. Can you try again? It should be fixed now and you should be able to link correctly to pytlsd.

**Comment by rpautrat** [comment]
I am closing this now as it should have been resolved now. If this is not the case, feel free to reopen it.
