### ISSUE TITLE
TypeError: lsd(): incompatible function arguments. The following argument types are supported:

### ISSUE THREAD

**Issue by yuanhangzheng-code** [cvg/DeepLSD#10]
Has anyone encountered a similar problem?
I tried to install on ubuntu. Here is the traceback from jupyter:
TypeError: lsd(): incompatible function arguments. The following argument types are supported:
 1. (img: numpy.ndarray[numpy.float64], scale: float = 0.8, sigma_scale: float = 0.6, density_th: float = 0.0, gradnorm: numpy.ndarray[numpy.float64] = array([], dtype=float64), gradangle: numpy.ndarray[numpy.float64] = array([], dtype=float64)) -> numpy.ndarray[numpy.float32]

Invoked with: array([[100., 102., 103., ..., 111., 111., 113.],
       [101., 102., 103., ..., 111., 112., 113.],
       [104., 104., 104., ..., 112., 112., 113.],
       ...,
       [ 93.,  92.,  93., ..., 243., 241., 240.],
       [103., 103., 101., ..., 244., 244., 242.],
       [ 78.,  76.,  76., ..., 241., 241., 244.]]); kwargs: scale=1.0, gradnorm=array([[2.57419753, 2.52489138, 2.18968916, ..., 2.68456316, 2.77042079,
        2.80449152],
       [2.61466122, 2.35479498, 1.70597696, ..., 2.60563469, 2.84062576,
        2.75185728],
       [2.58136368, 2.45527935, 2.25546384, ..., 2.19458222, 2.5106287 ,
        2.68859076],
       ...,
       [3.71072507, 3.71005678, 3.70416141, ..., 2.97271562, 2.40432501,
        1.80609179],
       [3.29464531, 3.19876194, 3.17765403, ..., 2.25287461, 1.85981727,
        1.52646542],
       [2.83806252, 2.7701757 , 2.65922499, ..., 1.6292944 , 1.41910815,
        1.35227203]]), gradangle=array([[-1024.        , -1024.        , -1024.        , ...,
        -1024.        , -1024.        , -1024.        ],
       [-1024.        , -1024.        , -1024.        , ...,
        -1024.        , -1024.        , -1024.        ],
       [-1024.        , -1024.        , -1024.        , ...,
        -1024.        , -1024.        , -1024.        ],
       ...,
       [-1024.        ,     5.99458066,     6.0488495 , ...,
        -1024.        , -1024.        , -1024.        ],
       [-1024.        ,     6.04460517,     6.05717483, ...,
        -1024.        , -1024.        , -1024.        ],
       [-1024.        , -1024.        , -1024.        , ...,
        -1024.        , -1024.        , -1024.        ]]), grad_nfa=True

**Comment by rpautrat** [comment]
Hi, I think that you have the wrong version of pytlsd installed. In your version, the grad_nfa option is missing. You should be using this one: https://github.com/rpautrat/pytlsd
Before installing this one, make sure to have removed any previous installation of pytlsd on your machine.

**Comment by yuanhangzheng-code** [comment]
> 
Thanks for your reply, can I use “pip uninstall pytlsd” to remove any previous installation of pytlsd on my machine？

**Comment by yuanhangzheng-code** [comment]
> Hi, I think that you have the wrong version of pytlsd installed. In your version, the grad_nfa option is missing. You should be using this one: https://github.com/rpautrat/pytlsd
> Before installing this one, make sure to have removed any previous installation of pytlsd on your machine.

thanks :) The code successfully runs

**Comment by rpautrat** [comment]
Glad to hear that :)
