### ISSUE TITLE
A small bug when running evaluate_line_detection.py

### ISSUE THREAD

**Issue by hjshxb** [cvg/DeepLSD#15]
Hi, 
When running `evaluate_line_detection.py`, an IndexError occurs due to [match_lines()](https://github.com/cvg/DeepLSD/blob/23c9cb71187119f6479d2b88940798a8c626cb3e/deeplsd/models/lbd.py#L56).
The `my_matches` array of type float, because the `pytlbd.lbd_matching_multiscale()` also returns descriptor distances. 
So would raise `IndexError: arrays used as indices must be of integer (or boolean) type`

To fix this issue, replace line [66](https://github.com/cvg/DeepLSD/blob/23c9cb71187119f6479d2b88940798a8c626cb3e/deeplsd/models/lbd.py#L66) with:
```
pred_matches[my_matches[:, 0].astype(np.int32)] = my_matches[:, 1].astype(np.int32)
```
Finally, Your work has been incredibly helpful to me.

**Comment by rpautrat** [comment]
Thanks a lot for reporting it, I just pushed the change: https://github.com/cvg/DeepLSD/commit/6593ead5970a7145c22480f5580c91f344a9422e
