### ISSUE TITLE
train run fail

### ISSUE THREAD

**Issue by githublqs** [cvg/DeepLSD#17]
DeepLSD/deeplsd/models/deeplsd.py", line 17, in <module>
    from line_refinement import line_optim
ImportError: /lib/libgdal.so.30: undefined symbol: GEOSMakeValidWithParams_r

how to solve this problem ,thanks!

**Comment by rpautrat** [comment]
Hi, I have never seen this error before.
What was the output of the `bash install.sh` command? Did everything installed correctly?

**Comment by githublqs** [comment]
thanks i solved , i replace it with a litter higher version of the lib, i found in the install output, mine opencv-python version is 4.7 which called this lib




---Original---
From: "Rémi ***@***.***&gt;
Date: Tue, Apr 4, 2023 20:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cvg/DeepLSD] train run fail (Issue #17)




 
Hi, I have never seen this error before.
 What was the output of the bash install.sh command? Did everything installed correctly?

**Comment by rpautrat** [comment]
Ok great, glad to hear that you could solve it by upgrading your library.
