### ISSUE TITLE
what is the way to estimate homography with Line Feature in your job

### ISSUE THREAD

**Issue by BambValley** [cvg/DeepLSD#18]
Thanks a lot for your wonderful job!
I notice that it has been mentioned in paper that the homography is estimated like the way of Super Point, while point is different from line.
Could you tell me how exactly the homography is estimated in your job?
Does the end point of matched line regard as the same point feature so that the homography estimation for point could work?

**Comment by rpautrat** [comment]
Hi,

We use the following repository to compute the homography, both from points and lines: https://github.com/rpautrat/homography_est/

In the case of lines, we do not use the line endpoints, but use a solver that considers infinite lines. The minimal number of lines to obtain the homography is in this case 4.
I hope this answers your question.

**Comment by BambValley** [comment]
> Hi,
> 
> We use the following repository to compute the homography, both from points and lines: https://github.com/rpautrat/homography_est/
> 
> In the case of lines, we do not use the line endpoints, but use a solver that considers infinite lines. The minimal number of lines to obtain the homography is in this case 4. I hope this answers your question.

It's really helpful. Thanks for your reply!

**Comment by BambValley** [comment]
> Hi,
> 
> We use the following repository to compute the homography, both from points and lines: https://github.com/rpautrat/homography_est/
> 
> In the case of lines, we do not use the line endpoints, but use a solver that considers infinite lines. The minimal number of lines to obtain the homography is in this case 4. I hope this answers your question.

It's really helpful. Thanks for your reply!
