### ISSUE TITLE
A question about Math

### ISSUE THREAD

**Issue by GK615Lab** [cvg/DeepLSD#19]
Firstly I am very interested in your work and I think it do broaden my horizon.
After running the demo, I have a question: after line refinement, is there any mathematical expressions with the detected lines.
Because I want to do Visual Line Matching baesd on your nice work.
SINCERELY!
Wish for your answer.

**Comment by rpautrat** [comment]
Hi, I am not sure to properly understand your question. What do you mean exactly by "mathematical expression with the detected lines"?

In case you want to do line matching, you might be interested in our recent work doing this: https://github.com/cvg/GlueStick.

**Comment by GK615Lab** [comment]
Thank you very much for your so quick answer!
