### ISSUE TITLE
fatal: Could not read from remote repository. “git clone --recurse-submodules git@github.com:cvg/DeepLSD.git” can’t work

### ISSUE THREAD

**Issue by Xuduoteng** [cvg/DeepLSD#2]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rpautrat** [comment]
Hi, when did you clone/fork the repository? I fixed one of the dependency (pytlsd) a few days ago solving a similar issue. Maybe you should try again cloning it now?

Aternatively, what is your full error message? I cannot know which dependency is causing your error without the full error.

**Comment by Xuduoteng** [comment]
Thank you very much for your quick reply, your work on line segment detection is certainly very meaningful. I reran the command on my server and got the following results, I don't know if the error is due to my personal reasons,







Jayden
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cvg/DeepLSD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月21日(星期三) 晚上6:20
***@***.***&gt;;
抄送:&nbsp;"Duoteng ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cvg/DeepLSD] fatal: Could not read from remote repository. “git clone --recurse-submodules ***@***.***:cvg/DeepLSD.git” can’t work (Issue #2)





 
Hi, when did you clone/fork the repository? I fixed one of the dependency (pytlsd) a few days ago solving a similar issue. Maybe you should try again cloning it now?
 
Aternatively, what is your full error message? I cannot know which dependency is causing your error without the full error.

**Comment by Xuduoteng** [comment]
![bd70ed49e247da9723e5d0edac547db](https://user-images.githubusercontent.com/62707393/208886327-3b5a27f4-7e63-4a2d-be72-55a591017a92.png)

**Comment by Xuduoteng** [comment]
I reran the command on my server and got the following results, I don't know if the error is due to my personal reasons,
![1671619452562](https://user-images.githubusercontent.com/62707393/208886795-b692562b-7b44-4875-a053-76f769e4cc29.png)

**Comment by rpautrat** [comment]
This is surprising, because the repo should be public, and this error message usually happens for private repos you don't have access to...

Do you get the same by just running `git clone git@github.com:cvg/DeepLSD.git`?

Please make sure also that your ssh key is correct (if you are using ssh authentication) and that you can clone other git repositories as well.

**Comment by rpautrat** [comment]
Hi, did you solve your problem?

**Comment by Xuduoteng** [comment]
It works when using `git clone --recurse-submodules https://github.com/cvg/DeepLSD.git`.

**Comment by rpautrat** [comment]
Great, yes we fixed that yesterday to use https to clone.
I am closing this now, since this has been solved.
