### ISSUE TITLE
How to optimise DeepLSD with ortho-image ?

### ISSUE THREAD

**Issue by aquexexl** [cvg/DeepLSD#20]
Hi guys!
Thank you for your work !
I work with image from scan 3D like cut or front of a building
![18045-fac-principale_inf (6)](https://github.com/cvg/DeepLSD/assets/71713669/9a5fd544-cde2-4c3c-bccf-b2fd225101b5)
Is it possible to work and optimize this type of image with no perspective or angle ?
Do I have to change some parameters ?
Thank you !

**Comment by rpautrat** [comment]
Hi, at test time you only need a single image as input. So it should work fine with the default parameters I think, if your images are similar to the ones you show here.

**Comment by aquexexl** [comment]
Okay thank you for your answer. Do I have to change some parameter for the training, I have created a new wireframe dataset with my own images. I had to cut my images in mosaique (some images are 10000x5000)

**Comment by rpautrat** [comment]
The large resolution of images might indeed be an issue. DeepLSD is usually working on images of side 500-1000 px. For larger resolutions, the lines will become much more fragmented and noisy. But if each sub-image in your mosaique is smaller than 1000 px, the default parameters should be fine I think. The released model has been trained with 512x512 images for example.
