### ISSUE TITLE
Can this be applied in gluestick?

### ISSUE THREAD

**Issue by Graysonggg** [cvg/DeepLSD#22]
Hello, wondeful work !

Your research in Gluestick says learned line detectors struggle to generalize power to other contexts, tasks, or types of images, so you choose LSD. I am considering that have you ever consider using this half-learned & half-manual DeepLSD as the line detector component of Gluestick and what are the reasons for not using it?

Looking forward to your reply very much！

**Comment by rpautrat** [comment]
Hi, yes we did try GlueStick with DeepLSD, and we obtain the best results with this combination. For example, DeepLSD+GlueStick is the default line detector+matcher in our other repo [LIMAP](https://github.com/cvg/limap) (3D line reconstruction and visual localization).

**Comment by Graysonggg** [comment]
Thank you for your so quick reply.
