### ISSUE TITLE
Can use sAP to evaluate this method, i know that output does not contain confident socre of predicted line.

### ISSUE THREAD

**Issue by nghiabka** [cvg/DeepLSD#23]

**Comment by rpautrat** [comment]
Hi, you could engineer a line score, by either using the NFA score returned by LSD (but it is probably noisy), or sampling the distance field along the line and average it to get one score.

But computing the sAP (eg on the Wireframe dataset) for DeepLSD does not make too much sense anyway. It is not trained to detect wireframe lines and is instead a more generic line detector. That is why we used repeatability, localization error, and downstream tasks to evaluate it in the paper.
