### ISSUE TITLE
third party packages failed to build 

### ISSUE THREAD

**Issue by tal-grossman** [cvg/DeepLSD#3]
## System:
- ubuntu 20.04
- python 3.8 / 3.9 / 3.6

## Steps Taken:
- git clone including recursive (as the readme suggests)
- install ceres
- bash install.sh
[build_failure_log.txt](https://github.com/cvg/DeepLSD/files/10302708/build_failure_log.txt)

  - pip requirement installed sucssesfuly
  - `progressive-x` lib failed to build due to 
 1. `fatal error: Python.h: No such file or directory`
 2. 
> Could not find a package configuration file provided by "glog" with any of
  the following names:
[build_failure_log.txt](https://github.com/cvg/DeepLSD/files/10302701/build_failure_log.txt)

    glogConfig.cmake
    glog-config.cmake
3. more errors 

## Additional information
1. tried to build with a terminal sourced to basrhc (normally) and via venv as well. 
2. Fixed the first error by changing the path of the python libs in the cmakelist.txt but still error accured 

log attached

**Comment by rpautrat** [comment]
Hi, thanks for the detailed bug report.

1. Do you have the Ubuntu package `python-dev` installed on your machine? Running `sudo apt install python-dev` should solve this issue.
2. I had a similar issue with this library. My fix was to modify the CMakeLists.txt of the progressive-x repo as follows:
Replace lines 93-96 with:
```
# find_package(glog REQUIRED)
# if(NOT glog_FOUND)
#      message(FATAL_ERROR "Glog not found.")
# endif()
find_package(PkgConfig REQUIRED)
pkg_check_modules(glog REQUIRED libglog)
```
And each time there is a call to `glog::glog` (3 times in total), use this instead: `${glog_LIBRARIES}`.
This assumes that you have the Ubuntu package `libgoogle-glog-dev` installed on your machine.

3. In the following errors, there is one about CUDA: "OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.". You should make sure that you have CUDA correctly installed on your machine. In my case, the code was running fine for CUDA 10.1.

**Comment by rpautrat** [comment]
I am closing this now. Feel free to reopen it if your issues were not solved.
