### ISSUE TITLE
PINTO model zoo ONNX models for DeepLSD work. How to get from heatmaps to line segments?

### ISSUE THREAD

**Issue by ogencoglu** [cvg/DeepLSD#31]
[PINTO_model_zoo](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/339_DeepLSD) converted your models to onnx for inference-time optimization and they indeed work out of the box.

Several models are provided:

```
deeplsd_md_180x320.onnx		deeplsd_wireframe_225x400.onnx
deeplsd_md_225x400.onnx		deeplsd_wireframe_240x320.onnx
deeplsd_md_240x320.onnx		deeplsd_wireframe_270x480.onnx
deeplsd_md_270x480.onnx		deeplsd_wireframe_360x640.onnx
deeplsd_md_360x640.onnx		deeplsd_wireframe_450x800.onnx
deeplsd_md_450x800.onnx		deeplsd_wireframe_480x640.onnx
deeplsd_md_480x640.onnx		deeplsd_wireframe_540x960.onnx
deeplsd_md_540x960.onnx		deeplsd_wireframe_720x1280.onnx
deeplsd_md_720x1280.onnx	        deeplsd_wireframe_HxW.onnx
deeplsd_md_HxW.onnx                  deeplsd_wireframe_180x320.onnx
```

and inference can be made with simple:

```
lsd_model = InferenceSession(
    "deeplsd_md_HxW.onnx",
    providers=["CPUExecutionProvider"],
)
input_name = lsd_model.get_inputs()[0].name
output = lsd_model.run(None, {input_name: image})
```

output consists of 3 numpy arrays that are the same shape as input image. I believe these are the probability heatmaps/fields.

Is there a straightforward way to infer the line segments using these 3 numpy arrays? If so, which function(s) I should be looking at in the codebase?

**Comment by ogencoglu** [comment]
netron.app shows the three heads of the onnx model as such:
![image](https://github.com/cvg/DeepLSD/assets/8182738/bcb826ce-b503-41ad-9a54-687d21464a9a)

Do these correspond to `angle_head` and `df_head` in [_forward](https://github.com/cvg/DeepLSD/blob/6dc642429677ecffb51c694d0a8dfbec9243db79/deeplsd/models/deeplsd_inference.py#L72)? What would the 3rd output correspond to? Any help would be appreciated.

**Comment by rpautrat** [comment]
Hi, this is great, I did not know about this!

Yes, the output 308 corresponds to the angle field (the `outputs['line_level']`), and the output 297 to the distance field (`outputs['df']`). The third output can be ignored, it is a normalized version of the distance field that is only used during training.

To extract the line segments from these two outputs, you need to run the rest of the pipeline, which is located here: https://github.com/cvg/DeepLSD/blob/25b037ad81413f057abbeb9de705dc09d6c86fb0/deeplsd/models/deeplsd_inference.py#L88-L97
This will convert the distance and angle field to an image gradient and run the LSD line detector to extract the lines.

**Comment by ogencoglu** [comment]
Cool, I will try that. Thanks a lot!
