### ISSUE TITLE
Does DeepLSD assume the coordinates of the center of the upper left pixel to be (0, 0) or (0.5, 0.5)?

### ISSUE THREAD

**Issue by xulongbai** [cvg/DeepLSD#33]
Hi, thanks for the great work!
Does DeepLSD assume the coordinates of the center of the upper left pixel to be (0, 0) or (0.5, 0.5)?

**Comment by rpautrat** [comment]
Hi, as far as I remember, DeepLSD was trained by assuming that the origin is on the top left of the top left corner. In other words, an endpoint with coordinates (0, 0) is located exactly on the top left corner of the image.
