### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key optimize

### ISSUE THREAD

**Issue by KunningZheng** [cvg/DeepLSD#34]
Hello, thank you for your work.
When exporting line detections on York Urban, I met the error of missing key optimize. I didn't modify anything of the configs and everything went well with other datasets.
Here is the output in terminal.
![image](https://github.com/cvg/DeepLSD/assets/130332032/eb7a7c13-3b8b-4b9d-ac27-5029a5fb6eb0)

**Comment by rpautrat** [comment]
Hi, thank you for reporting this. Can you pull the latest changes and try again? This should be fixed now.

**Comment by KunningZheng** [comment]
It works! Thanks for help!
