### ISSUE TITLE
Angle Field Visualization Code

### ISSUE THREAD

**Issue by ibaiGorordo** [cvg/DeepLSD#4]
Hi,

How can I get the angle field visualization to look similar to the bottom left image in your README?

I have tried using [get_flow_vis()](https://github.com/cvg/DeepLSD/blob/main/deeplsd/geometry/viz_2d.py#L191) by passing **out['df']** and **out['line_level']** as inputs, but I get the following image.

![flow_img](https://user-images.githubusercontent.com/43162939/209601731-8ce0d07e-3a37-4488-b428-7111c48060a9.png)

I understand that the lines and points require additional code, but the flow part also doesn't look similar to the README, should I use a different code? Or, is line_level, not the correct variable?

Thanks!

**Comment by rpautrat** [comment]
Hi, line_level should be the right variable. What command did you use exactly to plot it? If I plot `get_flow_vis(out['df'][0].cpu().numpy(), out['line_level'][0].cpu().numpy())`, I get the following image:
![angle](https://user-images.githubusercontent.com/32239569/209794309-ba1e5068-c2d0-49c5-b38f-bd7cb055462f.png)

**Comment by ibaiGorordo** [comment]
Thanks for the quick reply. I realize now that the only difference was that I was plotting the image in OpenCV, so I had to set `convert_to_bgr=True` in **flow_vis.flow_to_color()**. Then, I got the same output.

Thanks!
