### ISSUE TITLE
export the DeepLSD model to ONNX

### ISSUE THREAD

**Issue by rangingwaves** [cvg/DeepLSD#42]
How can I export the DeepLSD model to ONNX? Can you teach me?

**Comment by rpautrat** [comment]
Hi, I never did it, but the network is pretty simple, so you should be able to follow any good tutorial to export to ONNX.

**Comment by rangingwaves** [comment]
@rpautrat Thank you for your excellent work! I successfully exported the ONNX model, but I encountered some issues. However, I have used the ONNX model provided by PINTO_model_zoo and successfully converted its output into line segments using your code. I plan to deploy the model in my work next.
