### ISSUE TITLE
homography_adaptation_df.py crashes on num_jobs >1 

### ISSUE THREAD

**Issue by asbe** [cvg/DeepLSD#7]
Hi, 
I am running this script with `joblib==1.2.0`, and the script crashes on start with the following output. Changing backend from `loky` to e.g. `multiprocessing` lets the script run seemingly normal. (Edited for brevity)

Not sure if this is an issue with joblib or an unfortunate combination of library-versions? Can you possibly share a pip freeze or similar of known good combinations? 

```
joblib.externals.loky.process_executor._RemoteTraceback: 
[...]
TypeError: cannot pickle 'PyCapsule' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...]
  File "/home/asbe/projects/SWIFTER/DeepLSD/deeplsd/scripts/homography_adaptation_df.py", line 178, in <module>
    export_ha(args.images_list, args.output_folder, args.num_H,
  File "/home/asbe/projects/SWIFTER/DeepLSD/deeplsd/scripts/homography_adaptation_df.py", line 159, in export_ha
    Parallel(n_jobs=n_jobs, backend='loky')(delayed(process_image)(
  [...]
  File "/home/asbe/anaconda3/envs/deeplsd/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

**Comment by rpautrat** [comment]
Hi, I also get the same error with the 'loky' backend actually. I was using the parallelization in a previous version of the code not using cuda, where 'loky' was working, but in the current version using cuda, 'loky' does not work. Since 'multiprocessing' seems to work, I just changed it to this one.

Thanks for reporting the issue!
