### ISSUE TITLE
executing in windows

### ISSUE THREAD

**Issue by MahdiMohseni0033** [cvg/DeepLSD#8]
Does your code also run in Windows?

**Comment by rpautrat** [comment]
Hi, I have never tried it on Windows, but I don't expect it to run out of the box with this OS... The development was made under Linux.

Unfortunately I can't bring support for Windows, as I am never using it.

**Comment by MahdiMohseni0033** [comment]
Oh, I understand.
I appreciate your wonderful job and your quick response.
